//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by game.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_PRACTICE                    157
#define IDB_BLUE                        158
#define IDB_WHITE                       158
#define IDB_BITMAP3                     159
#define IDB_GREEN                       159
#define IDB_BLACK                       159
#define IDB_BACKGROUN                   160
#define IDB_BACKGROUND1                 160
#define IDB_BACK                        168
#define IDB_BITMAP4                     170
#define IDB_BACK2                       176
#define IDB_MAN5                        178
#define IDB_MAN1                        179
#define IDB_MAN2                        180
#define IDB_MAN3                        181
#define IDB_MAN4                        182
#define IDB_BACK3                       183
#define IDB_BITMAP5                     184
#define IDB_RED                         184
#define IDB_BACKRUN                     187
#define IDB_BITMAP6                     188
#define IDB_FIRE                        188
#define IDB_BITMAP7                     215
#define IDB_a10                         215
#define IDB_a1                          216
#define IDB_a2                          217
#define IDB_a3                          218
#define IDB_a4                          219
#define IDB_a5                          220
#define IDB_a6                          221
#define IDB_a7                          222
#define IDB_a8                          223
#define IDB_a9                          224
#define IDB_BITMAP8                     225
#define IDB_BACKGROUND                  225
#define IDB_UP                          228
#define IDB_DOWN                        230
#define IDB_BITMAP9                     231
#define IDB_BESTSCORE                   233
#define IDB_BEST                        234
#define IDB_BITMAP10                    235
#define IDB_YOURSCORE                   235
#define IDB_BITMAP11                    237
#define IDB_GOLD                        237
#define IDB_STAR                        239
#define IDB_SUPER0                      242
#define IDB_SUPER1                      243
#define IDB_SUPER2                      244
#define IDB_BITMAP15                    245
#define IDB_SUPER3                      245
#define IDB_SLIP0                       246
#define IDB_SLIP1                       247
#define IDB_SLIP2                       248
#define IDB_SLIP3                       249
#define IDB_SLIP4                       250
#define IDB_SLIP5                       251
#define IDB_SLIP6                       252
#define IDB_SLIP7                       253
#define IDB_DIE0                        254
#define IDB_DIE1                        255
#define IDB_DIE2                        256
#define IDB_BITMAP16                    257
#define IDB_DIE3                        257
#define IDB_STARTVIEW1                  258
#define IDB_STARTVIEW2                  259
#define IDB_STARTVIEW3                  260
#define IDB_STARTVIEW4                  261
#define IDB_STARTVIEW5                  262
#define IDB_ROADBLOCK                   263
#define IDB_ROADBLOCK1                  264
#define IDB_OVER0                       265
#define IDB_OVER1                       266
#define IDB_OVER2                       267
#define IDB_BITMAP17                    268
#define IDB_OVER3                       268
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        269
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
